TechnoStore/TechnoStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('', include('blog.urls')),
    path('', include('products.urls')),
    path('', include('user.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

TechnoStore/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name = 'blog')
]

TechnoStore/info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('', views.home, name = 'default'),
    path('home/', views.home, name = 'home'),
    path('contact/', views.contact, name = 'contact'),
    path('about/', views.about, name = 'about')
    
]

TechnoStore/products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('products/', views.products, name = 'products')
]

TechnoStore/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_views, name = 'login'),
    path('register/', views.register_views, name = 'register')
]

TechnoStore/blog/models.py
from django.db import models

# Create your models here.

TechnoStore/info/models.py
from django.db import models

# Create your models here.

class SliderImage(models.Model):
    image = models.ImageField(upload_to='slider-images/',null=False)
    
    

TechnoStore/products/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    
    
    def __str__(self):
        return self.name
    

class SubCategory(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name
    
class Products(models.Model):
    image = models.ImageField(upload_to='products/')
    title = models.CharField(max_length=85, null=False, blank=False)
    description = models.TextField(max_length=90, null=False, blank=False)
    old_price = models.CharField(max_length=10, null=False, blank=True)
    price = models.CharField(max_length=10, null=False, blank=False)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    discount = models.BooleanField(default=False)
    new = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.title

TechnoStore/user/models.py
from django.db import models

# Create your models here.

TechnoStore/blog/views.py
from django.shortcuts import render
from products.models import Category

# Create your views here.

def blog(request):
    categoryes = Category.objects.all()
    return render(request, 'blog.html', context={'categoryes': categoryes})

TechnoStore/info/views.py
from django.shortcuts import render
from products.models import Category, Products, SubCategory
from .models import SliderImage

# Create your views here.
def home(request):
    sliderimage = SliderImage.objects.all()
    categoryes = Category.objects.all()
    products = Products.objects.all()
    return render(request, 'index.html', context={'categoryes': categoryes, 'sliderimage': sliderimage, 'products': products})


def contact(request):
    categoryes = Category.objects.all()
    return render(request, 'contact.html', context={'categoryes': categoryes})


def about(request):
    categoryes = Category.objects.all()
    return render(request, 'about.html', context={'categoryes': categoryes})

TechnoStore/products/views.py
from django.shortcuts import render
from .models import Category, SubCategory, Products

# Create your views here.
def products(request):
    categoryes = Category.objects.all()
    return render(request, 'products.html', context={'categoryes': categoryes} )

TechnoStore/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

# Create your views here.

def login_views(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            login(request, user)
            return redirect('info:default')
        else:
            return render(request, 'login.html', {'error': "Istifadeci adi ve ya sifre yanlisdir"})    
            
    return render(request, 'login.html')

def register_views(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        repassword = request.POST['repassword']
        
        if password == repassword:
            if User.objects.filter(username = username).exists():
                return render(request, 'register.html', {"error": "Username basqasi terefinden istifade olunur"})
            else:
                if User.objects.filter(email = email).exists():
                    return render(request, 'register.html', {"error": "E-mail basqa birine aiddir"})
                else:
                    user = User.objects.create_user(first_name = firstname, last_name = lastname, username = username, email = email, password = password)
                    user.save()
                    return redirect('user:login')
                
        else:
            return render(request, 'register.html', {"error": "Sifreler uygun deyil"})

    return render(request, 'register.html')

TechnoStore/templates/about.html
{% extends 'layout/_header.html' %}
{% load static %}


{% block main %}

<main id="aboutMenu">
    <div class="custom-width">
        <div class="nameNote">
            <h3>Haqqımızda</h3>
        </div>
        <div class="about">
            <div class="row justify-content-between">
                <div class="col-lg-7 about-text">
                    <h4>TechnoStore Community </h4>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sapiente itaque illum autem
                        voluptatibus facilis! Aliquid molestiae non excepturi enim esse! Rem eius iste, hic enim
                        quibusdam fugiat nesciunt! Voluptatum velit dolorum nisi voluptatem et fugit obcaecati
                        maiores praesentium! Tempora est eveniet commodi quis autem aliquam similique mollitia
                        distinctio necessitatibus repudiandae ipsum omnis incidunt ipsa sit, esse suscipit minus
                        vitae ducimus ad? Ab, fuga in possimus, minima facilis aliquam quibusdam rerum expedita rem
                        iure nisi atque beatae magnam ducimus cumque libero repudiandae. Eaque rerum, ipsum eius
                        inventore labore error placeat, ipsa illo corporis ratione ad dicta voluptates? Recusandae
                        quia soluta cupiditate?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident,
                        totam vitae nostrum ut minima veritatis laboriosam numquam. Fuga officiis nemo accusamus ut
                        aliquam ipsa magnam optio est magni earum odit tempora, at totam alias dolore enim cum
                        ratione quam iusto distinctio soluta quis voluptatum laborum commodi. Reprehenderit aliquid
                        accusamus deleniti!</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore nostrum maiores labore,
                        commodi incidunt ex delectus nobis quibusdam mollitia placeat aliquid vero voluptate
                        obcaecati, sequi accusamus, deserunt cupiditate voluptatem molestias pariatur? Iste, illo!
                        Quos voluptatum placeat, delectus quidem corporis neque labore aut doloribus dolorem ut
                        harum illo quae dolores enim nulla! Eveniet, eum impedit perferendis nulla distinctio sint
                        dicta rem nostrum odio ut eligendi fuga blanditiis quaerat et reiciendis ullam!</p>
                </div>
                <div class="col-lg-4 about-image">
                    <div class="col-lg-12">
                        <img class="img-fluid photo" src={% static 'photo/TechnoStoreContact.jpeg' %} alt="">
                    </div>
                    <div class="col-lg-12">
                        <img class="img-fluid photo" src={% static 'photo/TechnoStoreContact2.jpg' %} alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock main %}


{% block scripts %}
    
<script src={% static 'vendors/js/jquery-3.6.0.min.js' %}></script>
<script src={% static 'vendors/js/bootstrap.bundle.js' %}></script>
<script src={% static 'layoutjs/layout.js' %}></script>

{% endblock scripts %}
 

TechnoStore/templates/blog.html
{% extends 'layout/_header.html' %}
{% load static %}






{% block scripts %}
    
<script src={% static 'vendors/js/jquery-3.6.0.min.js' %}></script>
<script src={% static 'vendors/js/bootstrap.bundle.js' %}></script>
<script src={% static 'layoutjs/layout.js' %}></script>

{% endblock scripts %}

TechnoStore/templates/contact.html
{% extends 'layout/_header.html' %}    <!-- ...............SECTION ONE START......url.............. -->
{% load static %}


    {% block main %}


        <main id="contactMenu">
            <div class="custom-width">
                <div class="nameNote">
                    <h3>Əlaqə</h3>
                </div>
                <!-- <div class="contact">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-lg-3 minibox adress">
                            <h5>Azərbaycan, Bakı</h5>
                            <p>Heydər Əliyev pr.</p>
                            <p>999A</p>
                        </div>
                        <div class="col-lg-3 minibox telephone">
                            <h5>Telefonlar</h5>
                            <p>+994 12 999 99 99</p>
                            <p>+994 50 999 99 99</p>
                        </div>
                        <div class="col-lg-3 minibox mail">
                            <h5>E-mail</h5>
                            <p>help@technostore.az</p>
                        </div>
                        <div class="col-lg-3 minibox socialmedia">
                            <a href="https://web.whatsapp.com/" target="_blank"><i class="fa-brands fa-whatsapp"></i></a>
                            <a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a>
                            <a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook-f"></i></a>
                        </div>
                    </div>
                </div> -->
                <div class="userMessage">
                    <div class="row justify-content-between align-items-start">
                        <div class="col-lg-5">
                            <div class="rowsbox">
                                <input class="firstname" type="text" data-error="Zehmet olmasa Adinizi daxil edin"
                                    placeholder="Adınız...">
                                <input class="lastname" type="text" data-error="Zehmet olmasa Soyadinizi daxil edin"
                                    placeholder="Soyadınız...">
                            </div>
                            <div class="colsbox">
                                <input type="text" data-error="Zehmet olmasa Telefon nomrenizi daxil edin"
                                    placeholder="Telefon...">
                                <input type="text" data-error="Zehmet olmasa E-mailinizi daxil edin"
                                    placeholder="E-mail...">
                                <textarea name="text" id="" cols="50" rows="10"
                                    placeholder="Müraciətinizi qeyd edin..."></textarea>
                                <a href="#">Müraciət Göndər</a>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <iframe
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d194473.42999466046!2d49.71487539548643!3d40.39450797992698!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307d6bd6211cf9%3A0x343f6b5e7ae56c6b!2sBak%C3%BC%2C%20Azerbaycan!5e0!3m2!1str!2s!4v1664664985374!5m2!1str!2s"
                                width="600" height="600" style="border:0;" allowfullscreen="" loading="lazy"
                                referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </main>

    {% endblock main %}

    {% block scripts %}
    
    <script src={% static 'vendors/js/jquery-3.6.0.min.js' %}></script>
    <script src={% static 'vendors/js/bootstrap.bundle.js' %}></script>
    <script src={% static 'layoutjs/layout.js' %}></script>
    
    {% endblock scripts %}

TechnoStore/templates/layout/_doctype.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Techno Store</title>
    <link rel="stylesheet" href={% static 'vendors/css/bootstrap.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>


{% block main %}



{% endblock main %}

TechnoStore/templates/layout/_header.html
{% load static %}




<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Techno Store</title>
    <link rel="stylesheet" href={% static 'vendors/css/bootstrap.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>



<body>

    <!-- <div class="icons">
        <img src="photo/cpu-tower.png" alt="">
    </div>
 -->

    <!-- ...............HEADER START.................... -->


    <header id="firstHeader">
        <div class="custom-width">
            <div class="d-flex justify-content-between align-items-center">
                <div class="menubaricon">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <div class="techLogo">
                    <div class="logo">
                        <a href={% url 'info:default' %}><img class="img-fluid" src={% static 'photo/logo.png' %} alt=""></a>
                    </div>
                </div>
                <div class="techMenu">
                    <ul class="list-unstyled d-flex align-items-center m-0 p-0">
                        <li class="is_active"><a href={% url 'info:home' %}>Ana Səhifə</a></li>
                        <li><a href={% url 'products:products' %}>Məhsullar</a></li>
                        <li><a href={% url 'info:about' %}>Haqqımızda</a></li>
                        <li><a href={% url 'blog:blog' %}>Bloq</a></li>
                        <li><a href={% url 'info:contact' %}>Əlaqə</a></li>
                    </ul>
                </div>
                <div class="rightmenuicon">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <div class="techRight d-flex align-items-center">
                    <div class="darkMode">
                        <i class="fa-solid fa-moon"></i>
                    </div>
                    <div class="userLogin">
                        <a href={% url 'user:login' %}>
                            Daxil ol
                        </a>
                    </div>
                    <div class="userRegister">
                        <a href={% url 'user:register' %}>
                            Qeydiyyat
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div id="secHeader">
        <div class="custom-width">
            <div class="d-flex justify-content-between align-items-center">
                <div id="category-button" class="category d-flex align-items-center">
                    <h3>Kateqoriyalar</h3>
                    <i class="fa-solid fa-bars-progress"></i>
                </div>
                <div class="openCategory" class="cat_active">
                    <ul class="list-unstyled m-0 p-0">
                        {% for category in categoryes %}
                            <li><i class="fa-solid fa-laptop"></i><a href="#">{{category.name}}</a></li>
                        
                        {% endfor %}
                    </ul>
                </div>
                <div class="searchNav">
                    <input placeholder="Məhsul Axtar" class="searchInput" type="search">
                    <a href="#"><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
                <div class="userProg">
                    <ul class="d-flex align-items-center list-unstyled">
                        <li class="shop-cart"><i class="cart-icon fa-solid fa-cart-shopping"></i><a href="#"></a></li>
                        <div class="cart-up">
                            <i class="triangel fa-solid fa-play"></i>
                            <i class="xmark fa-solid fa-xmark"></i>
                            <p>Sizin səbətiniz boşdur</p>
                        </div>
                        <li class="wishlist"><i class="fa-solid fa-heart"></i><a href="#"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- ...............HEADER END.................... -->


    {% block main %}{% endblock main %}


    <!-- ...............FOOTER START.................... -->

    <div id="footer">
        <div class="custom-width">
            <div class="content">
                <div class="top_content">
                    <img src={% static 'photo/logo.png' %} alt="">
                </div>
                <div class="bottom_content">
                    <span>TechnoStore 2022. All Copyright Reserved</span>
                </div>
            </div>
        </div>
    </div>
    <!-- ...............FOOTER END.................... -->

</body>


{% block scripts %}{% endblock scripts %}

TechnoStore/templates/login.html
{% extends 'layout/_doctype.html' %}
{% load static %}


{% block main %}


<div id="userLogin">
    <div class="log-box d-flex justify-content-center align items center">
        <div class="top-content">
           <a href={% url 'info:default' %}>
            <div class="logo">
                <img class="img-fluid" src={% static 'photo/logo.png' %} alt="">
            </div>
           </a> 
            <div class="content">
                <h4>Giriş Et</h4>
            </div>
        </div>
        <form action={% url 'user:login' %} method='POST'>
            {% csrf_token %}
            <div class="input-area">
                <label for="username" class="form-label"></label>
                <input type="text" placeholder="İstifadəçi adı və ya E-mail girin" name="username">
                <label for="password"></label>
                <input type="password" placeholder="Şifrənizi girin" name="password">
            </div>
            <div class="submit-btn">
                {% comment %} <a  href=''>Daxil ol</a> {% endcomment %}
                <button class='sub-btn' type="submit">Daxil ol</button>
            </div>
            <div class="btn-register">
                <span>Hesabın yoxdur?<a href={% url 'user:register' %}>Qeydiyyatdan Keç</a></span>
            </div>
        </form>
    </div>
</div>


{% endblock main %}

TechnoStore/templates/register.html
{% extends 'layout/_doctype.html' %}
{% load static %}


{% block main %}


<div id="userRegister">
    <div class="reg-box d-flex justify-content-center align items center">
        <div class="top-content">
            <a href={% url 'info:default' %}>
                <div class="logo">
                    <img class="img-fluid" src={% static 'photo/logo.png' %} alt="">
                </div>
            </a>
            <div class="content">
                <h4>Qeydiyyatdan Keç</h4>
            </div>
        </div>
        <form action={% url 'user:register' %} method="POST">
        {% csrf_token %}
        <div class="input-area">
            <label for="firstname" class='form-label'></label>
            <input class="firstname" type="text" placeholder="Ad" name="firstname">

            <label for="name" class='form-label'></label>
            <input class="surname" type="text" placeholder="Soyad" name="lastname">

            <label for="username" class='form-label'></label>
            <input class="username" type="text" placeholder="İstifadəçi adı" name="username">

            <label for="email" class='form-label'></label>
            <input class="email" type="email" placeholder="E-mail" name="email">

            <label for="password" class='form-label'></label>
            <input class="password" type="password" placeholder="Şifrənizi girin" name="password">

            <label for="repassword" class='form-label'></label>
            <input class="password" type="password" placeholder="Şifrənizi yenidən girin" name="repassword">

            {% comment %} <label for="check" class='form-label'></label>
            <input class="check" type="checkbox" > {% endcomment %}
            {% comment %} <span>Şərtlər və qaydalarla razıyam</span> {% endcomment %}
        </div>
        <div class="submit-btn">
            {% comment %} <a href="#">Qeydiyyat</a> {% endcomment %}
            <button type="submit">Qeydiyyatdan Kec</button>
        </div>


        </form>
        <div class="btn-login">
            <span>Hesabın var?<a href={% url 'user:login' %}>Giriş Et</a></span>
        </div>
    </div>
</div>


{% endblock main %}